<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>demotiff1</name>
   <tag></tag>
   <elementGuidId>d6b2b26f-0188-4bdf-b808-3e02ff6e3094</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//SPAN[@ng-bind='file.FileName'][text()='DEMO_001_Pages.tiff']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
