<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>demotiff3</name>
   <tag></tag>
   <elementGuidId>59df92e1-38b2-4a1f-967e-ef04301b1de8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//SPAN[@ng-bind='file.FileName'][text()='DEMO_005_Pages.tiff']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
