<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Demotiff2</name>
   <tag></tag>
   <elementGuidId>0f382626-12c7-4120-9e71-6980e5147573</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//SPAN[@ng-bind='file.FileName'][text()='DEMO_002_Pages.tiff']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
