<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subcategory</name>
   <tag></tag>
   <elementGuidId>811a616e-561b-4608-881a-fa44e8ff699d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div/div/div[2]/div[2]/div/div[1]/div[2]/div/div/div[2]/div[2]/div/div/select</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
